version: "3.7"

services:
  node:
    container_name: node
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./react-sample:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
